- generators/server/files.js
- generators/server/templates/build.gradle.ejs
- generators/server/templates/gradle.properties.ejs
- generators/server/templates/gradle/profile_dev.gradle.ejs
- generators/server/templates/settings.gradle.ejs
- generators/server/templates/src/test/java/package/security/DomainUserDetailsServiceIT.java.ejs
This makes gradle a viable option for the `"generator-jhipster.buildTool"` on the CLI prompt / `.yo-rc.json`.
One should be able to generate a project and utilize `./gradlew run` instead of `./mvnw compile exec:exec` and run the project as the maven equivalent runs
> #14 adds gradle support

- generators/entity-server/templates/src/main/java/package/common/field_validators.ejs
> Chore: Removes the TODO around the @Size field validator for blobs (#21)

- README.md
- generators/constants.js
- generators/server/prompts.js
- generators/server/templates/gradle.properties.ejs
- generators/server/templates/pom.xml.ejs
- generators/server/templates/src/main/java/package/config/CacheConfiguration.java.ejs
- generators/server/templates/src/main/java/package/util/JHipsterProperties.java.ejs
This add caffeine support to generated application.
This also aligns the jhipster dependencies version with the main generator and uses the jib version defined in the main generator.
closes #46
> provide caffeine cache implementation

- generators/entity-server/templates/src/main/java/package/service/mapper/EntityMapper.java.ejs
MapStruct allows generating jsr330 beans, which is what micronaut is using.
https://mapstruct.org/documentation/dev/reference/pdf/mapstruct-reference-guide.pdf
Method annotated with `componentMapping="spring"` causes strange initialisation-runtime error as spring stereotype component isn't in classpath, but it's referenced from code in target/. Error is not visible in intellij or maven as mappers are not part of the codebase.
> Use jsr330 componentModel in EntityMapper

- generators/common/templates/README.md.ejs
- generators/entity-server/templates/src/main/java/package/common/get_filtered_template.ejs
- generators/entity-server/templates/src/main/java/package/service/EntityQueryService.java.ejs
- generators/entity-server/templates/src/main/java/package/service/EntityService.java.ejs
- generators/entity-server/templates/src/main/java/package/service/impl/EntityServiceImpl.java.ejs
- generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs
> Use javax @Transaction and micronaut @ReadOnly on service methods

- generators/server/templates/build.gradle.ejs
- generators/server/templates/pom.xml.ejs
increase upper bounds for supported java version from 13 to 14.
closes #127
> support java 14 as highest java version

- generators/heroku/index.js
- generators/heroku/templates/Procfile.ejs
When building a jar with maven we have two jars:
* xyz.jar (which is the exeutable jar) and
* original-xyz.jar
The procfile just started `*.jar` in case the app name was before `o` everything worked fine. In case the original jar was lexicographical before the executable jar it was tried to start that. In the main generator we don't have that problem as the original jar is named xyz.jar.original so we could just reference `*.jar`.
closes #126
> Fix heroku deployement for app names starting with "p" or later

- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
inject mapstruct mappers as they are used in the tests
closes #105
> inject and import dto mappers when used for an entity in tests

- generators/heroku/index.js
- generators/heroku/templates/StrictTransportSecurityHeaderFilter.java.ejs
- generators/server/files.js
- generators/server/templates/src/main/java/package/security/SecurityHeaderFilter.java.ejs
- generators/server/templates/src/test/java/package/security/SecurityHeaderFilterTest.java.ejs
Adds the same security headers as we have for spring boot. The Strict-Transport-Security is only added for heroku right now as we can't make sure ssl is used e.g. in prod profile (of course it should)
close #124
CC @mraible guess you like this :tada:
> add security headers

- generators/server/templates/pom.xml.ejs
This makes `./mvnw` also compile the frontend (and doing java tests). Editing a java class makes the micronaut plugin just compiling the class and changes are available directly in the current running application.
> Executing just `./mvnw` compiles the frontend

- generators/heroku/templates/provision-okta-addon.sh.ejs
The auto provisioned users are added to both ROLE_ADMIN and ROLE_USER such that the entities page can be accessed.
closes #148
> add created user to both admin and user group/role

- generators/heroku/templates/Procfile.ejs
- generators/heroku/templates/application-heroku.yml.ejs
- generators/heroku/templates/pom-profile.xml.ejs
This sets the liquibase context when deploying to heroku in 
* properties (e.g. when using docker, gradle)
* in pom profile which is uses in the procfile
> Do not create fake data when deploying to heroku

- generators/heroku/index.js
- generators/heroku/templates/application-heroku.yml.ejs
- generators/server/templates/pom.xml.ejs
This fixes the entrypoint definition for jib (see main generator) and removes the jwt secret environment variable from heroku properties as there is a value now in prod profile
> Fix docker deployment for heroku

- generators/server/templates/src/main/resources/application-prod.yml.ejs
Somehow we missed this in `prod` properties
updates #168
> do not load faker data in prod environment

- generators/client/templates/angular/src/main/webapp/app/layouts/navbar/navbar.component.html.ejs
- generators/server/templates/src/main/java/package/App.java.ejs
- generators/server/templates/src/main/resources/application-dev.yml.ejs
- generators/server/templates/src/main/resources/h2.server.properties.ejs
While checking #168 I noticed the h2 db files are not under `/target`/`build`. I can't see any specific reason why we should not put them under the build output directory.
> create h2 db files in gradle build dir, support h2 console-ui

- generators/constants.js
The updated micronaut data version contains the needed fix for https://github.com/jhipster/generator-jhipster-micronaut/pull/193
> update micronaut data

- generators/entity-server/templates/src/test/java/package/common/validate_entity_fields_template.ejs
- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
This also fixes a Sonar warning about assertion arguments being passed in the wrong order
> Remove non assertj assertion

- generators/server/templates/build.gradle.ejs
> Removes temporary Liquibase resolution strategy in Gradle builds (#192)

- generators/server/templates/build.gradle.ejs
- generators/server/templates/pom.xml.ejs
This removes jcenter definition from pom.xml and build.gradle. Everything should be on central I think.
updates #223
> remove jcenter repo from maven and gradle build file

- README.md
- generators/app/__snapshots__/generator.spec.mjs.snap
- generators/server/__snapshots__/generator.spec.mjs.snap
- generators/server/files.cjs
- generators/server/templates/src/main/java/package/domain/User.java.ejs
- generators/server/templates/src/main/java/package/repository/UserRepository.java.ejs
- generators/server/templates/src/main/java/package/service/UserService.java.ejs
- generators/server/templates/src/main/java/package/service/dto/AdminUserDTO.java.ejs
- generators/server/templates/src/main/java/package/service/dto/UserDTO.java.ejs
- generators/server/templates/src/main/java/package/service/mapper/UserMapper.java.ejs
- generators/server/templates/src/main/java/package/web/rest/AccountResource.java.ejs
- generators/server/templates/src/main/java/package/web/rest/PublicUserResource.java.ejs
- generators/server/templates/src/main/java/package/web/rest/UserResource.java.ejs
- generators/server/templates/src/main/java/package/web/rest/vm/ManagedUserVM.java.ejs
- generators/server/templates/src/test/java/package/service/UserServiceIT.java.ejs
- generators/server/templates/src/test/java/package/service/mapper/UserMapperIT.java.ejs
- generators/server/templates/src/test/java/package/web/rest/AccountResourceIT.java.ejs
- generators/server/templates/src/test/java/package/web/rest/UserResourceIT.java.ejs
To separate the publicly accessible user information from the private one.
Porting https://github.com/jhipster/generator-jhipster/issues/12374
> Add AdminUserDTO and the PublicUserResource
