CODE_OF_CONDUCT.md
LICENSE

@sendilkumarn If you have some other tasks (e.g. adding the gradle template or so) just ping me, happy to help with micronaut!
closes #2

add code of conduct from main project

---

cli/mhipster.js
generators/server/files.js
generators/server/index.js
generators/server/prompts.js

Related to https://github.com/jhipster/generator-jhipster/pull/11048

Update Copyright Headers for 2020

---

generators/client/files.js
generators/client/templates/angular/src/main/webapp/app/core/login/login.service.ts.ejs
generators/client/templates/angular/src/main/webapp/app/layouts/navbar/navbar.component.html.ejs
generators/client/templates/angular/src/main/webapp/app/layouts/navbar/navbar.component.ts.ejs
generators/client/templates/angular/src/test/javascript/e2e/admin/administration.spec.ts.ejs
generators/client/templates/angular/webpack/webpack.dev.js.ejs
generators/client/templates/react/src/main/webapp/app/modules/login/logout.tsx.ejs
generators/client/templates/react/src/main/webapp/app/shared/reducers/authentication.ts.ejs
generators/client/templates/react/src/test/javascript/e2e/modules/administration/administration.spec.ts.ejs
generators/client/templates/react/src/test/javascript/spec/app/modules/administration/administration.reducer.spec.ts.ejs
generators/client/templates/react/src/test/javascript/spec/app/shared/reducers/authentication.spec.ts.ejs
generators/client/templates/react/webpack/webpack.dev.js.ejs
generators/server/files.js
generators/server/templates/build.gradle.ejs
generators/server/templates/pom.xml.ejs
generators/server/templates/src/main/docker/app.yml.ejs
generators/server/templates/src/main/java/package/security/ApiLogoutController.java.ejs
generators/server/templates/src/main/java/package/security/JHipsterOpenIdUserDetailsMapper.java.ejs
generators/server/templates/src/main/java/package/security/KeycloakEndSessionEndpoint.java.ejs
generators/server/templates/src/main/java/package/security/Logout.java.ejs
generators/server/templates/src/main/java/package/web/rest/ClientForwardController.java.ejs
generators/server/templates/src/main/resources/application.yml.ejs

Adds OAuth2 dependencies (Maven & Gradle), configuration, user details mapper (extracts username and roles from OpenID JWT), and modifications to the Angular and React clients to support OAuth2/OIDC flow.

OAuth2 Support

---

generators/constants.js

Updates Micronaut to 1.3.5

---

generators/server/templates/build.gradle.ejs
generators/server/templates/gradle.properties.ejs
generators/server/templates/settings.gradle.ejs

Use the shadow plugin to generate executable jars
closes #83

use shadow plugin to generate executable jars

---

generators/server/templates/build.gradle.ejs
generators/server/templates/pom.xml.ejs

https://micronaut-projects.github.io/micronaut-data/latest/api/io/micronaut/data/model/Pageable.html
Closes #99
Add package which provides ` io.micronaut.data.model.Pageable`

micronaut-data-runtime is required to support pagination

---

README.md

Just that, use the contributed micronaut family member in the readme

use micronaut family member

---

generators/server/files.js
generators/server/templates/src/main/java/package/web/rest/UserResource.java.ejs
generators/server/templates/src/test/java/package/web/rest/UserResourceIT.java.ejs
test-integration/samples/gradle-jwt-react.jdl
test-integration/samples/mvn-no-client.jdl
test-integration/samples/mvn-oauth-angular.jdl

There is still a bit of work remaining here.  The generated Java tests haven't been updated yet and don't compile.  I think once the tests are working this should be mostly ready to go.

Fixes relationships between entities and User

---

generators/entity-server/templates/src/main/java/package/common/get_all_template.ejs

Adding the missing `,` to the findAll template
closes #98

add missing ',' to method definition for findAllX

---

generators/entity-server/templates/src/main/java/package/service/dto/EntityDTO.java.ejs
generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs

put introspected on dtos such that they can be validated

---

generators/constants.js
generators/server/templates/build.gradle.ejs

Updates 
* micronaut to 2.0.1
* micronaut data to 1.1.3 and
* jackson to 2.11.1
This should fix #122

update micronaut to 2.0.1

---

generators/entity-server/files.js
generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs
test-integration/samples/mvn-oauth-angular.jdl

Fixes issues encountered during validation of "Space" application

---

generators/server/templates/pom.xml.ejs
generators/server/templates/src/main/resources/application-prod.yml.ejs

closes #140 
closes #139 
closes #137

Fixes Maven and Docker configuration issues

---

generators/constants.js
generators/server/templates/src/main/resources/application-dev.yml.ejs
generators/server/templates/src/main/resources/application-prod.yml.ejs
test-integration/samples/mvn-oauth-angular.jdl

Fix DB Dialect and Configuration issues

---

generators/client/files.js
generators/server/templates/src/main/java/package/security/SecurityUtils.java.ejs
generators/server/templates/src/main/resources/application.yml.ejs

Manifest.webapp should be available without auth

---

generators/server/templates/src/main/resources/application-dev.yml.ejs

Changes H2 Disk DB location to remove second target folder

---

generators/server/templates/src/main/java/package/security/SecurityHeaderFilter.java.ejs
generators/server/templates/src/test/java/package/security/SecurityHeaderFilterTest.java.ejs

remove invalid feature policy 'speaker'

---

generators/heroku/index.js

check for 'err' in callback and only log message on failure

---

generators/client/templates/angular/src/main/webapp/app/admin/health/health.service.ts.ejs
generators/client/templates/react/src/main/webapp/app/modules/administration/health/health-modal.tsx.ejs
generators/client/templates/react/src/main/webapp/app/modules/administration/health/health.tsx.ejs
generators/server/templates/src/main/resources/application.yml.ejs

Also fixes some missing i18n in the React client.
Closes #147

Fixes jdbc translation keys in client apps

---

generators/heroku/templates/Procfile.ejs
generators/heroku/templates/application-heroku.yml.ejs

To support easier docker deployment.

set the port in heroku properties instead of procfile

---

generators/server/templates/pom.xml.ejs

activate webpack dev by default instead of checking the dev bundle file

---

generators/server/prompts.js
generators/server/templates/build.gradle.ejs
generators/server/templates/pom.xml.ejs
generators/server/templates/src/main/java/package/repository/UserRepository.java.ejs
generators/server/templates/src/main/java/package/service/UserService.java.ejs
generators/server/templates/src/test/java/package/web/rest/UserResourceIT.java.ejs
test-integration/samples/mvn-no-client.jdl
test-integration/scripts/04-server-tests.sh

Fixes issues where User resources were attempting to use a cache even if one was not configured

---

README.md
generators/constants.js
generators/server/prompts.js
generators/server/templates/pom.xml.ejs
generators/server/templates/src/main/docker/app.yml.ejs
generators/server/templates/src/main/docker/mariadb.yml.ejs
generators/server/templates/src/main/resources/application-dev.yml.ejs
generators/server/templates/src/main/resources/application-prod.yml.ejs
test-integration/samples/mvn-jwt-redis-angular.jdl

Support MariaDB

---

generators/entity-server/templates/src/main/java/package/service/EntityQueryService.java.ejs

Singleton and Transactional imports were missing

Adding missing imports

---

generators/constants.js
generators/server/templates/build.gradle.ejs
generators/server/templates/gradle.properties.ejs
generators/server/templates/pom.xml.ejs
generators/server/templates/src/main/java/package/service/MailSenderFactory.java.ejs
generators/server/templates/src/main/java/package/service/MailService.java.ejs
generators/server/templates/src/main/resources/application-dev.yml.ejs
generators/server/templates/src/main/resources/application-prod.yml.ejs
generators/server/templates/src/test/java/package/service/MailServiceIT.java.ejs
generators/server/templates/src/test/java/package/web/rest/AccountResourceIT.java.ejs

This PR uses http://www.simplejavamail.org to replace the spring java mailing integration.
closes #31

activate mail sending 

---

generators/constants.js

Hopefully just as easy as this.

upgrade micronaut to 2.0.2

---

generators/constants.js

https://github.com/micronaut-projects/micronaut-data/releases/tag/v2.0.0
https://github.com/micronaut-projects/micronaut-core/releases/tag/v2.1.0 (to be published)

Upgrade micronaut-data to 2.0.0 and micronaut-core to 2.1.0

---

generators/common/templates/README.md.ejs
generators/server/files.js
generators/server/templates/build.gradle.ejs
generators/server/templates/gradle.properties.ejs
generators/server/templates/gradle/docker.gradle.ejs
generators/server/templates/settings.gradle.ejs
test-integration/scripts/06-build-app.sh

Replaces jib generator with micronaut-gradle-plugin.
Closes #113

Use micronaut-gradle plugin

---

generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
generators/server/templates/src/test/java/package/config/timezone/HibernateTimeZoneIT.java.ejs
generators/server/templates/src/test/java/package/security/DomainUserDetailsServiceIT.java.ejs
generators/server/templates/src/test/java/package/security/jwt/JWTFilterTest.java.ejs
generators/server/templates/src/test/java/package/security/jwt/TokenProviderTest.java.old
generators/server/templates/src/test/java/package/service/MailServiceIT.java.ejs
generators/server/templates/src/test/java/package/service/UserServiceIT.java.ejs
generators/server/templates/src/test/java/package/service/mapper/UserMapperIT.java.ejs
generators/server/templates/src/test/java/package/web/rest/AccountResourceIT.java.ejs
generators/server/templates/src/test/java/package/web/rest/ClientForwardControllerIT.java.ejs
generators/server/templates/src/test/java/package/web/rest/UserJWTControllerIT.java.ejs
generators/server/templates/src/test/java/package/web/rest/UserResourceIT.java.ejs
generators/server/templates/src/test/java/package/web/rest/errors/ExceptionTranslatorIT.java.ejs

Replace deprecated test annotation

---

generators/constants.js

update micronaut to 2.1.1

---

generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
test-integration/samples/gradle-jwt-react.jdl

Fix test compilation failure when using serviceClass or serviceImpl

---

generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
generators/server/templates/src/test/java/package/web/rest/TestUtil.java.ejs
test-integration/samples/mvn-no-client.jdl

Handle required relationships for SQL entities in integration tests

---

generators/server/templates/src/main/resources/application-dev.yml.ejs
generators/server/templates/src/main/resources/application-prod.yml.ejs
generators/server/templates/src/test/resources/application-test.yml.ejs

micronaut detects then using introspections now
As per comment on gitter from @graemerocher and commit https://github.com/micronaut-guides/micronaut-data-access-jpa-hibernate/commit/9c36ffadb5c4adbcfb7bdba86f552a94274eba32

Remove packages-to-scan

---

generators/entity/index.js

@atomfrede I think we should reconsider just removing this question for the time being until support is ready from #193 
@murdos What are your thoughts?

Removes filtering question from entity

---

generators/constants.js
generators/server/templates/build.gradle.ejs
generators/server/templates/gradle/docker.gradle.ejs

Bump micronaut to 2.2.3 and micronaut base docker images

Bump micronaut 2.2.3

---

generators/server/templates/src/main/resources/application-dev.yml.ejs
generators/server/templates/src/main/resources/application-prod.yml.ejs

update template to generate logging configuration that micronaut understands: https://docs.micronaut.io/latest/guide/index.html#propertySource
I spent some time trying to configure debug and trace for hibernate... until I figured this out.

update template to generate logging configuration works with micronaut 

---

generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs

fix compilation error when using Post as entity name

---

.github/workflows/generator.yml
.github/workflows/samples.yml
docker/Dockerfile

Related with https://github.com/jhipster/generator-jhipster/issues/14304

Update Nodejs version to 14.16.0

---

generators/entity-server/templates/src/main/java/package/common/save_template.ejs
generators/entity-server/templates/src/main/java/package/repository/EntityRepository.java.ejs
generators/entity-server/templates/src/main/java/package/service/EntityService.java.ejs
generators/entity-server/templates/src/main/java/package/service/impl/EntityServiceImpl.java.ejs
generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs
generators/server/templates/src/main/java/package/repository/UserRepository.java.ejs
generators/server/templates/src/main/java/package/service/UserService.java.ejs
generators/server/templates/src/test/java/package/service/UserServiceIT.java.ejs

Remove use of mergeAndSave

---

generators/constants.js
generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs
generators/heroku/templates/SSLEnforcingHostResolver.java.ejs
generators/server/templates/src/main/java/package/security/JHipsterEndSessionEndpoint.java.ejs
generators/server/templates/src/main/java/package/web/rest/AccountResource.java.ejs
generators/server/templates/src/main/java/package/web/rest/errors/handlers/ProblemHandler.java.ejs
generators/server/templates/src/test/java/package/config/timezone/HibernateTimeZoneIT.java.ejs
generators/server/templates/src/test/java/package/service/MailServiceIT.java.ejs

Also cleans up some compile warnings.

Updates to Micronaut 2.4.2

---

README.md

Add note about eureka/oauth issues and compatibility matrix which might be more relevant in the future.

update readme with release relevant information

---

generators/constants.js
generators/server/templates/gradle.properties.ejs

Updates Micronaut to 2.4.4

---

generators/server/templates/src/main/java/package/security/JHipsterEndSessionEndpoint.java.ejs

Break DI Loop in JHipsterEndSessionEndpoint (#220)

---

generators/server/templates/gradle/docker.gradle.ejs
generators/server/templates/pom.xml.ejs

tag docker image with latest and project version

---

generators/server/generator.js

Fix end message to say Micronaut

---

.github/workflows/samples.yml
generators/micronaut/command.js
generators/micronaut/generator.js
generators/server/command.js
generators/server/generator.js

- move prompts overrides back to server generator
- add config structure to micronaut generator

prompt adjusts

---

generators/micronaut/__snapshots__/generator.spec.js.snap
generators/micronaut/generator.spec.js

Make the 'with gradle build tool' test actually use Gradle and add a new test for Maven.
Because of the wrong configuration it was using the default Maven.

Fix snapshot tests for build tool

---

generators/bootstrap-application-base/generator.js

Related to https://github.com/jhipster/generator-jhipster/issues/27433

cleanup workaround

---

.github/workflows/merge.yml

Related to https://github.com/jhipster/generator-jhipster/issues/28188

download Micronaut bom with dependabot
